# Generated by Django 6.0.5 on 2026-08-18 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_ward_complaint_address_complaint_assigned_to_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_by_email',
            field=models.BooleanField(default=True, help_text='Email me when one of my complaints changes status.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='complaints.ward'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='10-digit mobile number.', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('corporator', 'Corporator')], db_index=True, default='citizen', max_length=20),
        ),
    ]
