# Generated by Django 6.0.5 on 2026-09-30 19:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('complaints', '0002_ward_complaint_address_complaint_assigned_to_and_more'),
        ('users', '0002_alter_customuser_options_customuser_notify_by_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='notify_by_email',
            field=models.BooleanField(default=True, help_text='Email me when one of my complaints changes status or gets an official reply.'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_user_email_ci', violation_error_message='An account with this email already exists.'),
        ),
    ]
