# Generated by Django 6.0.5 on 2026-05-09 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('garbage', 'Garbage'), ('road', 'Road Damage'), ('water', 'Water Supply'), ('streetlight', 'Streetlight')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='complaints/')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
