# Generated by Django 6.0.5 on 2026-08-18 18:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(default='Pune', max_length=80)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'corporator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], db_index=True, default=2),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='complaints/%Y/%m/thumbs/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, upload_to='complaints/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='issue_type',
            field=models.CharField(choices=[('garbage', 'Garbage'), ('road', 'Road Damage'), ('water', 'Water Supply'), ('streetlight', 'Streetlight'), ('drainage', 'Drainage / Sewage'), ('stray', 'Stray Animals'), ('encroachment', 'Encroachment'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('is_official', models.BooleanField(default=False, help_text='Set automatically when the author is a corporator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Seen'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint')),
            ],
            options={
                'verbose_name_plural': 'status history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='complaints.complaint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.ward'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='cmp_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', '-created_at'], name='cmp_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['ward', 'status'], name='cmp_ward_status_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['complaint', 'created_at'], name='cmt_cmp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['complaint', '-created_at'], name='hist_cmp_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='upvote',
            constraint=models.UniqueConstraint(fields=('complaint', 'user'), name='unique_upvote_per_user'),
        ),
    ]
