# Generated by Django 6.0.5 on 2026-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_ward_complaint_address_complaint_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='kind',
            field=models.CharField(choices=[('status', 'Status change'), ('priority', 'Priority change'), ('assignment', 'Assignment'), ('ward', 'Ward transfer')], default='status', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('seen', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('seen', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
